### PR TITLE
Added TweenAction.MOVETOTRANSFORM

### PR DESCRIPTION
**Pull request by freddiehonohan**
It goes without saying that if the transform is not static that the tween may or may not complete. Effectively it is a Move-Towards-Transform function.

### CODE REVIEW

**Comment by dentedpixel** [comment]
This looks good, I am working on a new app store submission, but once I am done with that I will merge this into the master branch.

**Comment by freddiehonohan** [comment]
Sweet, good luck with the new submission... Cheers!

**Comment by dentedpixel** [comment]
Hi Freddie,
I wasn't able to merge this pull request directly, but I added in your functionality in the commit: de3c630

I am calling the method just move like all the other moves, but it takes in a destination of a transform instead of the regular Vector3.

**Comment by freddiehonohan** [comment]
No worries Russell, fantastic engine you're overseeing here.

**Comment by dentedpixel** [comment]
Thanks! :)

On Tue, Nov 3, 2015 at 8:48 AM, freddiehonohan <notifications@github.com>
wrote:

> No worries Russell, fantastic engine you're overseeing here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dentedpixel/LeanTween/pull/54#issuecomment-153357816>.
>



-- 
Twitter - http://twitter.com/DentedPixel
Facebook - http://www.facebook.com/DentedPixel
Website - http://dentedpixel.com

**Pull request closed without merging**
