### PR TITLE
Cleaned up unused code and added onUpdateFloatRatio

### PR DESCRIPTION
**Pull request by 00christian00**
Hi,
I cleaned up some code that didn't do anything and added a new method to call a function by passing also the current ratio.

### CODE REVIEW

**Comment by dentedpixel** [comment]
Hi Christian,
Thanks for contributing. I use the mapping because without it a tween along a curve with one set of nodes close together and another set far away, would go slowly through the first set, and then quickly through the second set (and this is a linear tween so you would want it to move at a constant rate). So unfortunately I cannot remove that.

I like the idea of the setOnUpdateRatio and being able to adjust the rotation while on a curve. I looked into that a bit myself, but it was just easier to put the gameobject in a parent gameobject that you move along the path, and then you can rotate and move the child object from within...  I know one more gameobject that needs to be used, so it's not ideal.

**Comment by 00christian00** [comment]
Hi,
Maybe that was the plan initially for map, but right now you are just adding lengthRatio[i] and then substracting it from t, so in the end you always return either t or 1 just like my code.
I tested it at runtime and there is no difference, every segment get the exact same runtime regardless of the length. And anyway even if you fix it, I think the rationale behind is broken because you are calculating the linear distance between the points, but the curve can be much longer.

Regarding the rotation while on the curve, I still haven't managed to do it properly :( 
For compactness I would like to use the spline point transform to control the rotation, like this one:
https://www.assetstore.unity3d.com/en/#!/content/17194
I had a look at its code but it's too complex for me...

The reason behind extracting the ratio was because I wanted to use the ease curves, but I noticed these are calculated later directly with the tween values, so in the end now I am using an AnimationCurve evaluated at runtime with the ratio as input, so right now the curves are handled by unity itself.
Taking the Pathspline.cs example I use something like this on update:
cr.place(avatar1.transform, curve.Evaluate(iter));

Anyway the setOnUpdateRatio is a handy method because there is no way at the moment to know the current ratio in Leantween.

**Comment by dentedpixel** [comment]
Hi Christian,
I am hoping to look at this code very soon, I have been on vacation so I am
a little behind, but I just wanted to make sure you knew I wasn't ignoring
it.  You could be correct about the mapping stuff, I do not remember
confirming this work carefully, which I will have to do now.  Let me know
if you make any progress on the rotation on a curve stuff.

On Wed, Mar 4, 2015 at 9:21 AM, 00christian00 <notifications@github.com>
wrote:

> Hi,
> Maybe that was the plan initially for map, but right now you are just
> adding lengthRatio[i] and then substracting it from t, so in the end you
> always return either t or 1 just like my code.
> I tested it at runtime and there is no difference, every segment get the
> exact same runtime regardless of the length. And anyway even if you fix it,
> I think the rationale behind is broken because you are calculating the
> linear distance between the points, but the curve can be much longer.
>
> Regarding the rotation while on the curve, I still haven't managed to do
> it properly :(
> For compactness I would like to use the spline point transform to control
> the rotation, like this one:
> https://www.assetstore.unity3d.com/en/#!/content/17194
> I had a look at its code but it's too complex for me...
>
> The reason behind extracting the ratio was because I wanted to use the
> ease curves, but I noticed these are calculated later directly with the
> tween values, so in the end now I am using an AnimationCurve evaluated at
> runtime with the ratio as input, so right now the curves are handled by
> unity itself.
> Taking the Pathspline.cs example I use something like this on update:
> cr.place(avatar1.transform, curve.Evaluate(iter));
>
> Anyway the setOnUpdateRatio is a handy method because there is no way at
> the moment to know the current ratio in Leantween.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dentedpixel/LeanTween/pull/41#issuecomment-77165416>.
>



-- 
Twitter - http://twitter.com/DentedPixel
Facebook - http://www.facebook.com/DentedPixel
Website - http://dentedpixel.com

**Comment by 00christian00** [comment]
Hi,
Enjoy your vacation then! For my need Leantween is doing more than enough
as it is.
I solved the rotation on the curve. I ended up using esternal gameobjects
 so that I could have more control points than the actual curve point, but
maybe it's possible to integrate the concept into Leantween.
I am using what I call "gravity box", some collider whose rotation is used
as target rotation of the object. The object on to be moved on the path has
a child object that specify the current local rotation offset, and on
update I rotate the object by this child object rotation. I apply it every
frame because the lookat function reset the rotation every time, if you
remove the lookat you need to reset the rotation yourself or it will spin
endlessly :)
Then whenever the object enter a "gravity box" the child object start a
tweening from localeulerangles toward that box rotation angle and in turn
the parent object itself start rotating.



2015-03-11 14:51 GMT+01:00 dentedpixel <notifications@github.com>:

**Comment by 00christian00** [comment]
Hi, 
I made some new changes:
bug: onCompleteOnStart was being called only on delayedCall, now it's always called on every tween init.

Added onStart for similar function, but not tied to complete.
Added a new moveSplineLocal that accept an already instanced LTSpline.

**Comment by dentedpixel** [comment]
Hi Christian,
I wasn't able to automatically merge this code in, but I did try and get all the changes by hand editing them in.  Let me know if I missed anything! 

Thanks for your contribution.

**Pull request closed without merging**
