### PR TITLE
Provide interfaces for LeanTween and LTDescr classes

### PR DESCRIPTION
**Pull request by paulis**
Currently, LeanTween is used through LeanTween classe's static methods. This makes unit testing my own classes using leantween a bit tricky because there is no way to tweak the behavior of lean tween. Therefore, I have interfaced everything in lean tween so I can use it better with NUnit and NSubstitute testing libraries.

Like this:

```C#
public class TweeningCounter
{
	private readonly ILeanTween tweener;
	private readonly GameObject tweenable;
	private int count;

	public TweeningCounter(ILeanTween tweener, GameObject tweenable)
	{
		this.tweener = tweener;
		this.tweenable = tweenable;
	}
	public int Count { get { return this.count; } }

	public void Operation()
	{
		this.tweener.value(this.tweenable, 0f, 1f, 1f)
			.setEase(LeanTweenType.linear)
			.setOnComplete(() => {
				this.count++;
			});
	}
}

/// And the test for tweening counter

[TestFixture]
public class TweeningCounterTest
{
	[TestCase]
	public void MyCountIsIncreasedAfterOperationCompletes()
	{
		var leantTween = Substitute.For<ILeanTween>();
		var tweenable = new GameObject("tweenable");
		var myCounter = new TweeningCounter(leantTween,tweenable);

		var tween = Substitute.For<ILTDescr>();
		// All chaining methods return the same tween
		tween.setEase(Arg.Any<LeanTweenType>()).Returns(tween);
		tween.setOnComplete(Arg.Any<Action>()).Returns(tween);
		// Setting onComplete automatically immediately calls the on complete
		tween.When(t => t.setOnComplete(Arg.Any<Action>())).Do(x => x.Arg<Action>()());
		// Return the substitue tween when tweening value
		leantTween.value(Arg.Any<GameObject>(),Arg.Any<float>(),Arg.Any<float>(),Arg.Any<float>()).Returns(tween);

		Assert.AreEqual(0, myCounter.Count);
		myCounter.Operation();
		Assert.AreEqual(1, myCounter.Count);
	}
```

* Create ILeanTween interface based on public api of the LeanTween static methods.
* Create ILTDescr interface.
* Make LeanTween return ILTDescr objects instead of LTDescr from all its methods.
* Create LeanTweenImpl class to implement the ILeanTween. The LeanTweenImpl merely delegates all calls to existing LeanTween static methods.

### CODE REVIEW

**Comment by dentedpixel** [comment]
Hi Paulis,
Thanks for taking the time to work on this. I haven't done unit testing using Unity's tools yet, so forgive me if I am a little behind. I don't think we can change LeanTween's return object to ILTDescr though, this would break too many people's projects, if we do any change we will need to maintain backwards compatibility. Is there any way you can rework this to be more compatible to the current format?

**Comment by paulis** [comment]
Hi Russel!

Thanks for taking a look at my pull request.

Would it be possible that I change LeanTween.cs back to returning LTDescrs but the interface ILeantTween and it's implementation LeanTweenImpl would still return ILTDescrs? Then people could make a choice between using ILeanTween/LeanTweenImpl+ILTDescr or LeanTween+LTDescr. As long as LTDescr implements the ILTDescr interface I think this should be possible and not brake backwards compatibility.

-Pauli

**Comment by paulis** [comment]
Now I just renamed the interface to match the old class name:

ILTDescr -> LTDescr
and 
LTDescr to LTDescrImpl (implements LTDescr)

This way users can keep their code pointing to LTDescr but now it's just an interface instead of a concrete class and we still get the benefit of interfaces.

**Comment by dentedpixel** [comment]
Oh good! I was going to try to suggest something like this but I wasn't sure if it was possible given your setup. I am glad it is. Is there a way to provide an example scene with NUnit or NSubstitute? Or I guess that might require including the libraries (inside this library) which could get messy.... I just think it would be a great way to show people how to integrate those libraries with LeanTween (myself included, hehe)

**Comment by dentedpixel** [comment]
Hey Paulis,
Sorry this pull request hasn't been merged in sooner, if you don't have time to provide an NSubstitute or NUnit example, that is fine. Would you recommend one over the other?

**Comment by paulis** [comment]
Hi

Sorry for not having provided an example yet. My child was born so I've been quite busy elsewhere. 

NUnit and NSubstiute are usually used together so I would definitely use both. NUnit is a testing tool and NSubstitute supports testing by making mocking easy.

**Comment by dentedpixel** [comment]
Oh wow, 
╔═══╗─────────────╔╗───╔╗───╔╗
║╔═╗║────────────╔╝╚╗──║║──╔╝╚╗
║║─╚╬══╦═╗╔══╦═╦═╩╗╔╬╗╔╣║╔═╩╗╔╬╦══╦═╗╔══╗
║║─╔╣╔╗║╔╗╣╔╗║╔╣╔╗║║║║║║║║╔╗║║╠╣╔╗║╔╗╣══╣
║╚═╝║╚╝║║║║╚╝║║║╔╗║╚╣╚╝║╚╣╔╗║╚╣║╚╝║║║╠══║
╚═══╩══╩╝╚╩═╗╠╝╚╝╚╩═╩══╩═╩╝╚╩═╩╩══╩╝╚╩══╝
──────────╔═╝║
──────────╚══╝

No worries on the delay, I just didn't want this work to get lost forever, since it looks like you put a lot into it, and I think it could be helpful to others.

No rush though, of course spending time with your newborn is waaaay more important :)

**Comment by paulis** [comment]
Imported [UnityTestTools](https://www.assetstore.unity3d.com/en/#!/content/13802) to the project so we can run unit tests in unity. Locate "Unity Test Tools" in the to bar. Go "Unity Test Tools" -> "Unit Test Runner" -> "Run All". Currently, there is a single test which attempts to show how one would go about testing their own code while using LeanTween.

**Comment by dentedpixel** [comment]
Should this be run in Unity5.3? I am getting an error when trying to run it with 5.3, I tried updating the UnityTestTools to the latest with no luck. I am going to update the git repo to use the latest Unity as a base, so maybe we can try again with a merge into there?

**Comment by dentedpixel** [comment]
Hey Paulis,

I have gotten things working well, and I have merged over a lot of the changes you made into the master branch. For the time being I am going to keep the NUnit testing examples and framework portion in the "TestingToolsSupport" branch and not in the master, but since I have merged over a lot of the changes it should be easy enough to keep the two up to date. If you want to add any more tests to their I have granted you a collaborator status, and I may add more tests as I get to better understand NUnit.

Thanks for your help!
Russ

**Pull request merged**
